apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: blogposts.kube.zxl.com
spec:
  group: kube.zxl.com
  scope: Namespaced
  names:
    kind: BlogPost
    singular: blogpost
    plural: blogposts
    listKind: BlogPostList
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                title:
                  type: string
                url:
                  type: string
                publishdate:
                  type: string
                body:
                  type: string